baseurl = "/"
languageCode = "en-us"
title = "Estelle & Josh â€” Two people who like each other"
baseURL = "https://estelle.and.dzello.com/"
theme = ["reveal-hugo"]

[params]
description = "A compilation of our favorite stories and photos from when we met until now."
og_image = "https://estelle.and.dzello.com/images/assets/heart-frame.png"
og_image_width = 1600
og_image_height = 945

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
